### ISSUE TITLE
Housekeeping - Initial README.md

### ISSUE THREAD

**Issue by miosenpai** [gdgutm/Buddies#5]
This issue will be used to track the creation of the repo's README.md. Ideally, the following subjects should be included:
- Project Description
  - Features List
- Development Instructions
  - Git Workflow
  - Development Environment (IDEs, SDKs, etc)

**Comment by andy9775** [comment]
It should also include the steps to deploy the project locally and on AWS.

**Comment by miosenpai** [comment]
> It should also include the steps to deploy the project locally and on AWS.

We plan on expanding the README.md/other documentation files once we begin tackling on the corresponding tasks (we anticipate it will be difficult to document in a clear manner when we have not done any of the work). Documentation on the subject of deployment is now being tracked in #4.

**Comment by andy9775** [comment]
Of course. 

I’m just adding some of these comments so we don’t forget. 😀
