### ISSUE TITLE
User Story - Account Registration

### ISSUE THREAD

**Issue by miosenpai** [gdgutm/Buddies#6]
# Story Description

As a user, I would like to be able to create an account on the website so I can possess resources that are unique to me (e.g. a profile).

# Acceptance Criteria

- Account information should be stored inside a database.
  - Passwords **must** be hashed.
- Account information should be validated (duplicate emails, blank names, etc).
- API route `POST /api/v1/users/register`.
- UI.

# Additional Info

N/A

**Comment by andy9775** [comment]
In general, it's good practice to version your api, so `/api/v1/user/register`. Also, based on REST, resources should be plural, so `users` not `user`.

Further, are we using JWT and running our own auth system, firebase, auth0?

**Comment by miosenpai** [comment]
> In general, it's good practice to version your api, so `/api/v1/user/register`. Also, based on REST, resources should be plural, so `users` not `user`.

URLs have been updated for versioning.

> Further, are we using JWT and running our own auth system, firebase, auth0?

Our current plan is to use stateless authentication with JWT tokens (elaborated in #7).

**Comment by andy9775** [comment]
Are you implementing all of that your self? Auth0 for example supports JWT, but they provide all of the logic for the exchange. It could be something worth looking into as an alternative. 

My group last semester implemented everything on their own, but highly considered firebase/auth0

**Comment by miosenpai** [comment]
> Are you implementing all of that your self? Auth0 for example supports JWT, but they provide all of the logic for the exchange. It could be something worth looking into as an alternative.
> 
> My group last semester implemented everything on their own, but highly considered firebase/auth0

As discussed during last week's demo, we plan to implement authentication within our own application but we will relying on the Identity module of ASP.NET Core for features such as password hashing, token generation, roles, etc.
