### ISSUE TITLE
User Story - User Profile

### ISSUE THREAD

**Issue by miosenpai** [gdgutm/Buddies#8]
# Story Description

As a user, I would like to have an editable profile so I can inform other users about myself, my interests and my expertise.

# Acceptance Criteria

- Custom interests/skills can be added.
- "About Me" section (less than or equal 250 characters).
- "Headline" section (less than or equal 50 characters).
- Personal API route `PUT /api/v1/profiles` for updating profile.
- API route `GET /api/v1/profiles/:id` for fetching profile.
- **WIP**

# Additional Info

N/A

**Comment by andy9775** [comment]
Are we supporting deleting accounts? (`DELETE`)

**Comment by miosenpai** [comment]
> Are we supporting deleting accounts? (`DELETE`)

We'll place this feature on the backlog but we might not get to it in the January phase.
